### ISSUE TITLE
Jessie-in-Jessie

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Jessie#14]
Hi, (especially to @erights),

I'm interested in implementing Jessie-in-Jessie, which would be a metacircular interpreter/compiler along the lines of Ian Piumarta's [Maru](http://piumarta.com/software/maru/).  I think it would be interesting to experiment with how Jessie modules with ocap endowments and resource limitations can be used to construct a recursive implementation.

Notably, I'd like to stay away from existing Javascript implementations, to create something that would be minimal and easy to bootstrap on static platforms.  The focus for this effort would be to reduce the TCB as much as possible, as well as provide an implementation-language-agnostic ocap extension language library for existing programs.

Thoughts?

**Comment by erights** [comment]
Hi @michaelfig , that would be wonderful!! In fact, I've promised @brabalan I'd write one. Starting from a simple eval/apply style interpreter, he'd like to do a mechanized semantics of Jessie. IIUC, the semantics would be expressed in COQ and (among other things) used to produce an interpreter in OCaml (or some *ML family language). @brabalan , do I have that about right?

Does it sound like the kind of interpreter you're looking to start from aligns with the one @michaelfig proposes to write?

**Comment by brabalan** [comment]
This would be a great start indeed.

**Comment by michaelfig** [comment]
This project has been started in the [jessica](https://github.com/michaelfig/jessica) repository.

Please direct comments and questions there.
