### ISSUE TITLE
Avoiding `this` capture (use `bond()`)

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Jessie#19]
I would like to propose that we remove the requirement for avoiding `this` capture by:

```javascript
(1,some.method.here)(...args)
```

from Jessie.  Discussion below, please.

**Comment by michaelfig** [comment]
With a little thought, we could have something like `wrapFn`, which would be:

```javascript
function wrapFn(fnOrValue) {
  if (fnOrValue instanceof Function) {
    return (...args) => fnOrValue(...args);
  }
  return fnOrValue;
}
```

Then, every time we assign something to an array or object (not Maps, Sets or other objects with functional interface), we would insert a call to `wrapFn` (or its inlined equivalent) unless we know statically that the value is not a function.  This can be done by the compiler, just as you are proposing for `harden` in Jessie.

This would change method pointers to be more like Python: always carry the `self` around with the ponter, rather than Javascript where they can be detached.

Thanks,
Michael.

**Comment by erights** [comment]
Excellent! As an statically enforced practice for what appears in Jessie, it is unquestionably an improvement.

As for a compiler transform, that Jessie would run as an embedded language within a SES host, rather than directly as a subset of SES. I was thinking of introducing this level separation for some purposes anyway, but ala carte. I still want to be able to run Jessie programs as SES programs within SES systems, with the constraint that a correct Jessie program remain correct in this scenario. I can do this with your static checking rule, but not if the transform is hidden within a Jessie->SES compiler.

**Comment by erights** [comment]
I like this.

A nit:

```js
maybeMethod instanceof Function
```

is not a reliable test. I think you want

```js
typeof maybeMethod === 'function'
```

**Comment by erights** [comment]
Because of JavaScript's scoping rules, you can omit the `let _bonded;` at the top and just say

```js
const _bonded = makeWeakSet([bond]);
```
at the bottom.

**Comment by michaelfig** [comment]
Terrific, thank you!  I'm adding this to the Jessica TODO.md:

* See [Jessie this-capture issue](https://github.com/Agoric/Jessie/issues/19) and excise:

```javascript
foo.bar = other.obj.index;
(1,foo.bar)(baz)
```

in callers avoiding `this`-capture in favour of protecting callees:
```javascript
foo.bar = bond(other.obj, 'index');
foo.bar(baz)
```

**Comment by michaelfig** [comment]
Not sure about the scope rules you mentioned, if I do a `const bond = ...` later in the file, I get `ReferenceError: bond is not defined` when evaluating `const _bonded = makeWeakSet([bond])`.

It works when I change `bond` from an arrow constant to a function definition.

This is in node.js, v8.11.1.

**Comment by michaelfig** [comment]
The last part of this is that we also need to bond function values (as opposed to references) that cannot be statically proven to be arrow functions.  I suggest we use a single-argument bond in this case (index = undefined), and bind `this` to `null`.

Oh, and indexed-bond needs to be statically rejected for computed values that aren't numbers.  Unless they're a string literal.  Otherwise, bond can bypass Jessie's restrictions on computed indices.

...And bond needs to reject attempts to call with a non-object (or null) first argument.

This is getting hairy.  Is there something wrong with this API methodology, or is it just a complex subject?

You can follow [my implementation in jessica](https://github.com/michaelfig/jessica/tree/master/lib/bond.mjs) for what I currently have.

**Comment by dckc** [comment]
> Then, every time we assign something to an array or object ..., we would insert a call to `wrapFn` ...

That seems like it would change the meaning of some programs...

Does this preserve the property that Jessie is absorbed by SES and JavaScript?

**Comment by michaelfig** [comment]
@dckc, as @erights stated later, this would not be done by a compiler transform.  Instead, it would be statically required by Jessie to have the developer insert calls to `bond()` just as calls to `harden()` are statically required.

`bond()` would be part of `sesshim.js`.

**Comment by michaelfig** [comment]
As proposed in #27, `bond()` is unnecessary if `immunize()` transitively hardens its functions' `this` values as well.  Then, the only possible captured `this` is hardened objects.

I'm withdrawing this proposal in favour of immunize.  We can discuss further there, and reopen this proposal if absolutely necessary.
