### ISSUE TITLE
Allow trailing commas in Jessie object literals

### ISSUE THREAD

**Issue by katelynsills** [Agoric/Jessie#20]
@erights says: 

We should check that trailing commas are allowed in the Jessie grammar.

Jessie cannot require trailing commas, since Jessie is a superset of JSON and JSON does not allow trailing commas.

**Comment by erights** [comment]
I checked. They are not allowed by the current Jessie grammar. Changing the name of this issue to reflect that.

**Comment by dckc** [comment]
> Jessie cannot require trailing commas, since Jessie is a superset of JSON and JSON does not allow trailing commas.

I can't make sense of that. If Jessie were a _subset_ of JSON it could not allow trailing commas, but as a **superset**, it may.

**Comment by michaelfig** [comment]
This is resolved in [jessica](https://github.com/Agoric/Jessie/src/README.md).
