### ISSUE TITLE
Jessie grammar as missing documentation

### ISSUE THREAD

**Issue by darius** [Agoric/Jessie#41]
The README of this repo has a broken link to the Jessie grammar. I couldn't easily find the correct link in browsing around the Jessica repo on github. I gave up after trying a few different files and directories with semi-promising names in both repos.

**Comment by michaelfig** [comment]
The sources for the Jessie grammar in the jessica repo are (from top layer to bottom layer):

* [Jessie](https://github.com/agoric-labs/jessica/blob/master/lib/quasi-jessie.js.ts)
* [Justin](https://github.com/agoric-labs/jessica/blob/master/lib/quasi-justin.js.ts)
* [JSON](https://github.com/agoric-labs/jessica/blob/master/lib/quasi-json.js.ts)

Sorry this is not yet clearer.  My New Year's resolution will be to give some more attention to Jessie and jessica.  In the meantime, I'll at least update the README with this information.

**Comment by michaelfig** [comment]
The canonical link is now: https://github.com/agoric-labs/jessica#grammar

**Comment by darius** [comment]
Thanks!
